### ISSUE TITLE
External link broken

### ISSUE THREAD

**Issue by stevestrutt** [IBM-Bluemix-Docs/cis#14]
400 response when accessing
https://www.ibm.com/blogs/bluemix/2018/05/ibm-cloud-internet-services-ga/

Blog Post: IBM Cloud Internet Services: Protecting your web-facing workloads, one enhanced experience at a time

**Comment by sheltons** [comment]
There was an issue with the blog post that prevented the link from loading the post for some time. It has been corrected now, and should open again properly.
