### ISSUE TITLE
whitelist api returns error

### ISSUE THREAD

**Issue by ytama** [IBM-Bluemix-Docs/cis#18]
Hello,

On https://console.bluemix.net/docs/infrastructure/cis/whitelisted-ips.html, 
https://api.cis.cloud.ibm.com/v1/ips returns the following error. Could you check it?

400 Bad Request

Thanks,

**Comment by sheltons** [comment]
@ytama I did not receive an error when I ran it. Could you try again to be sure it wasn't a temporary problem?

**Comment by ytama** [comment]
Hi, now I can receive the correct response. Maybe it was a temporary problem.
We can close this issue.

Thanks,
