### ISSUE TITLE
Can't find pricing information

### ISSUE THREAD

**Issue by ketanpancholi** [IBM-Bluemix-Docs/cis#28]
A customer is interested in knowing about Pricing. I wasn't able to find a Pricing link on the CIS pages. Searching for Pricing on the search bar yielded "NO results" too.

**Comment by sheltons** [comment]
We made the decision to not put pricing information in the documentation itself, and leave it with the sales/OM teams to post. That way, if the price ever fluctuates, it is not dependent on docs to update, and won't inadvertently cause discrepancies that could open us up to being challenged.

@mzfarid Do you want to add any further input?

**Comment by sheltons** [comment]
No further input. Closing this issue for Docs Week.
