### ISSUE TITLE
incorrect nl folder structure

### ISSUE THREAD

**Issue by neal-timpe** [IBM-Bluemix-Docs/cis#29]
It looks to me like the translated content was not uploaded with the correct folder structure. https://github.com/IBM-Bluemix-Docs/cis/tree/master/nl

And the translations are not showing up. https://cloud.ibm.com/docs/cis?topic=cis-getting-started&locale=fr#getting-started

Remove the `cis` folder after `nl/_locale_` and it should work.

**Comment by sheltons** [comment]
I've removed the nested `cis` folders from each language subfolder. Please let me know if it's working now, @neal-timpe

**Comment by neal-timpe** [comment]
@sheltons That's the correct folder structure. It looks like the old tocs are missing the path values in the attributes, which is now the reason the translations don't render. If you have the new translation returns, I believe incorporating those will fix that.

**Comment by sheltons** [comment]
I will get the new files in place shortly. :)

**Comment by sheltons** [comment]
@neal-timpe I just uploaded the files, and they should be ready to recheck.

**Comment by neal-timpe** [comment]
This looks like french to me. closing https://cloud.ibm.com/docs/cis?topic=cis-getting-started&locale=fr#getting-started
