### ISSUE TITLE
Queston: Does CIS support differnet domain in a request header than what it's registered under

### ISSUE THREAD

**Issue by ranjeetbath** [IBM-Bluemix-Docs/cis#31]
Hello, I am trying to configure with a domain (eg: ibm.org.origin.net) but the requests taht will be handled by this CIS instance will come as ibm.org (redirected from IBM DNS to CIS).
I this supported by CIS ?

**Comment by bournemd** [comment]
Hi . Can you explain the usecase here ? It’s not quite clear what’s being asked here. Typically if you configure a (sub) domain in CIS requests for that domain will be handled. You can use page rules to specify host headers if you like. May be that’s what you are looking for ?

**Comment by sheltons** [comment]
This is more likely a question for Support, or the Sales Enablement team. 
Check out this page for further information about how to reach out to support: https://cloud.ibm.com/docs/infrastructure/cis?topic=cis-getting-help-and-support
Or go here to find a Sales team member to chat with: https://www.ibm.com/cloud/cloud-internet-services
